// src/integrations/qwik-ui/card.tsx
import { component$, Slot, type HTMLAttributes } from "@builder.io/qwik";
import { cn } from "~/lib/utils";

export type DivProps = HTMLAttributes<HTMLElement>;

const SdnCard = component$((props: DivProps) => {
  return (
    <div
      class={cn(
        "rounded-lg border bg-card text-card-foreground shadow-sm",
        props.class,
      )}
      {...props}
    >
      <Slot />
    </div>
  );
});

const SdnCardHeader = component$((props: DivProps) => (
  <div class={cn("flex flex-col space-y-1.5 p-6", props.class)} {...props}>
    <Slot />
  </div>
));

const SdnCardTitle = component$((props: HTMLAttributes<HTMLHeadingElement>) => (
  <h3
    class={cn(
      "text-2xl font-semibold leading-none tracking-tight",
      props.class,
    )}
    {...props}
  >
    <Slot />
  </h3>
));

const SdnCardDescription = component$(
  (props: HTMLAttributes<HTMLParagraphElement>) => (
    <p class={cn("text-sm text-muted-foreground", props.class)} {...props}>
      <Slot />
    </p>
  ),
);

const SdnCardContent = component$((props: DivProps) => (
  <div class={cn("p-6 pt-0", props.class)} {...props}>
    <Slot />
  </div>
));

const SdnCardFooter = component$((props: DivProps) => (
  <div class={cn("flex items-center p-6 pt-0", props.class)} {...props}>
    <Slot />
  </div>
));

export {
  SdnCard,
  SdnCardHeader,
  SdnCardFooter,
  SdnCardTitle,
  SdnCardDescription,
  SdnCardContent,
};

// src/integrations/shadcn/ui/card.tsx
/** @jsxImportSource react */
import * as React from "react";

import { cn } from "~/lib/utils";

const Card = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => (
  <div
    ref={ref}
    className={cn(
      "rounded-lg border bg-card text-card-foreground shadow-sm",
      className,
    )}
    {...props}
  />
));
Card.displayName = "Card";

const CardHeader = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => (
  <div
    ref={ref}
    className={cn("flex flex-col space-y-1.5 p-6", className)}
    {...props}
  />
));
CardHeader.displayName = "CardHeader";

const CardTitle = React.forwardRef<
  HTMLParagraphElement,
  React.HTMLAttributes<HTMLHeadingElement>
>(({ className, ...props }, ref) => (
  <h3
    ref={ref}
    className={cn(
      "text-2xl font-semibold leading-none tracking-tight",
      className,
    )}
    {...props}
  />
));
CardTitle.displayName = "CardTitle";

const CardDescription = React.forwardRef<
  HTMLParagraphElement,
  React.HTMLAttributes<HTMLParagraphElement>
>(({ className, ...props }, ref) => (
  <p
    ref={ref}
    className={cn("text-sm text-muted-foreground", className)}
    {...props}
  />
));
CardDescription.displayName = "CardDescription";

const CardContent = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => (
  <div ref={ref} className={cn("p-6 pt-0", className)} {...props} />
));
CardContent.displayName = "CardContent";

const CardFooter = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => (
  <div
    ref={ref}
    className={cn("flex items-center p-6 pt-0", className)}
    {...props}
  />
));
CardFooter.displayName = "CardFooter";

export {
  Card,
  CardHeader,
  CardFooter,
  CardTitle,
  CardDescription,
  CardContent,
};
